### ISSUE TITLE
Link misses information to find class types

### ISSUE THREAD

**Issue by bbottema** [dnault/therapi-runtime-javadoc#24] opened 2018-09-20 19:20 UTC
I'm trying to locate the actual Method object referenced by the Link.

Is it possible when creating Link objects to include the package relevant to the classname being referenced? Either the package is included in the class name itself, or the package comes from an import. It would take some trickery for sure, but the information could be very useful in runtime.

```java
public class Link {
    private final String label;
    private final String referencedPackage;
    private final String referencedClassName;
    private final String referencedMemberName;

    (..)
}
```

Alternatively, you could add a  list of all imports to ClassJavadoc so I can match it later manually. I imagine this to be a lot easier to implement in the short term.

```java
public class ClassJavadoc extends BaseJavadoc {

    private final List<Import> imports;
    private final List<FieldJavadoc> fields;
    private final List<FieldJavadoc> enumConstants;
    private final List<MethodJavadoc> methods;

    (..)
}
```

**Comment by dnault** [comment] 2018-09-21 16:37
Duplicate of #20.

Agreed, this is a real problem. The challenge is that there doesn't seem to be a standard way to get the imports.

**Closed as completed by dnault** 2018-09-21 16:37 UTC
Labels: duplicate
